spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: shopping_cart
      auto-index-creation: true

logging:
  level:
    root: INFO
    com.shopping.cart: INFO
    org.springframework.security: INFO
    org.springframework.data.mongodb: INFO
